import { InvoiceRecord, MatchStatus } from "./types";

// Small curated dataset to power the dashboard demo
export const invoices: InvoiceRecord[] = [
  {
    Invoice_ID: "INV-1001",
    Vendor_Number: "V100",
    Vendor_Name: "Acme Components",
    Material_Number: "MAT-01",
    Plant: "PL-01",
    PO_Number: "PO-5001",
    PO_Item: "10",
    PO_Type: "Standard",
    GR_Date: "2025-01-05",
    IR_Date: "2025-01-06",
    Match_Date: "2025-01-07",
    Resolution_Date: "2025-01-10",
    Payment_Date: "2025-02-10",
    Payment_Terms: "NET30",
    Match_Status: "PASS",
    Root_Cause_Code: undefined,
    Tolerance_Pass_Flag: false,
    Escalation_Flag: false,
    Exception_Type: undefined,
    Root_Cause: undefined,
    Confidence_Score: undefined,
    Cluster_ID: undefined,
    Suggested_Action: undefined,
    Block_Reason: undefined,
    Resolution_Suggestion: undefined,
    Responsible_Team: "AP Team",
    Auto_Release_Flag: true,
    SLA_Breach_Flag: false,
  },
  {
    Invoice_ID: "INV-1002",
    Vendor_Number: "V200",
    Vendor_Name: "Global Fasteners",
    Material_Number: "MAT-02",
    Plant: "PL-02",
    PO_Number: "PO-5002",
    PO_Item: "20",
    PO_Type: "Standard",
    GR_Date: "2025-01-12",
    IR_Date: "2025-01-13",
    Match_Date: "2025-01-20",
    Resolution_Date: "2025-02-02",
    Payment_Date: "2025-03-05",
    Payment_Terms: "NET45",
    Match_Status: "TOLERANCE_PASS",
    Root_Cause_Code: "QTY_TOL",
    Tolerance_Pass_Flag: true,
    Escalation_Flag: false,
    Exception_Type: undefined,
    Root_Cause: undefined,
    Confidence_Score: undefined,
    Cluster_ID: undefined,
    Suggested_Action: undefined,
    Block_Reason: undefined,
    Resolution_Suggestion: undefined,
    Responsible_Team: "AP Team",
    Auto_Release_Flag: true,
    SLA_Breach_Flag: false,
  },
  {
    Invoice_ID: "INV-1003",
    Vendor_Number: "V300",
    Vendor_Name: "Nordic Metals",
    Material_Number: "MAT-03",
    Plant: "PL-01",
    PO_Number: "PO-5003",
    PO_Item: "10",
    PO_Type: "Consignment",
    GR_Date: "2025-02-01",
    IR_Date: "2025-02-02",
    Match_Date: "2025-02-15",
    Resolution_Date: "2025-03-01",
    Payment_Date: "2025-03-30",
    Payment_Terms: "NET30",
    Match_Status: "FAIL",
    Root_Cause_Code: "PRICE_MISMATCH",
    Tolerance_Pass_Flag: false,
    Escalation_Flag: true,
    Exception_Type: "Price Deviation",
    Root_Cause: "Policy",
    Confidence_Score: 0.78,
    Cluster_ID: "C-12",
    Suggested_Action: "Request PO update",
    Block_Reason: "Price Block",
    Resolution_Suggestion: "Adjust PO price",
    Responsible_Team: "Procurement",
    Auto_Release_Flag: false,
    SLA_Breach_Flag: false,
  },
  {
    Invoice_ID: "INV-1004",
    Vendor_Number: "V100",
    Vendor_Name: "Acme Components",
    Material_Number: "MAT-02",
    Plant: "PL-03",
    PO_Number: "PO-5004",
    PO_Item: "30",
    PO_Type: "Standard",
    GR_Date: "2025-02-10",
    IR_Date: "2025-02-12",
    Match_Date: "2025-02-18",
    Resolution_Date: "2025-02-28",
    Payment_Date: "2025-04-01",
    Payment_Terms: "NET45",
    Match_Status: "FAIL",
    Root_Cause_Code: "MISSING_GR",
    Tolerance_Pass_Flag: false,
    Escalation_Flag: true,
    Exception_Type: "Missing GR",
    Root_Cause: "System",
    Confidence_Score: 0.62,
    Cluster_ID: "C-08",
    Suggested_Action: "Post GR",
    Block_Reason: "GR Block",
    Resolution_Suggestion: "Initiate GR",
    Responsible_Team: "Warehouse",
    Auto_Release_Flag: false,
    SLA_Breach_Flag: true,
    Block_Date: "2025-02-18",
  },
  {
    Invoice_ID: "INV-1005",
    Vendor_Number: "V400",
    Vendor_Name: "Zenith Plastics",
    Material_Number: "MAT-04",
    Plant: "PL-02",
    PO_Number: "PO-5005",
    PO_Item: "10",
    PO_Type: "Standard",
    GR_Date: "2025-03-02",
    IR_Date: "2025-03-04",
    Match_Date: "2025-03-05",
    Resolution_Date: "2025-03-09",
    Payment_Date: "2025-04-15",
    Payment_Terms: "NET30",
    Match_Status: "PASS",
    Tolerance_Pass_Flag: false,
    Escalation_Flag: false,
    Responsible_Team: "AP Team",
    Auto_Release_Flag: true,
    SLA_Breach_Flag: false,
  },
  {
    Invoice_ID: "INV-1006",
    Vendor_Number: "V300",
    Vendor_Name: "Nordic Metals",
    Material_Number: "MAT-05",
    Plant: "PL-01",
    PO_Number: "PO-5006",
    PO_Item: "40",
    PO_Type: "Standard",
    GR_Date: "2025-03-15",
    IR_Date: "2025-03-16",
    Match_Date: "2025-03-28",
    Resolution_Date: "2025-04-05",
    Payment_Date: "2025-05-10",
    Payment_Terms: "NET30",
    Match_Status: "TOLERANCE_PASS",
    Root_Cause_Code: "QTY_TOL",
    Tolerance_Pass_Flag: true,
    Exception_Type: "Minor Qty Diff",
    Root_Cause: "Policy",
    Confidence_Score: 0.55,
    Cluster_ID: "C-12",
    Suggested_Action: "Auto-approve",
    Block_Reason: undefined,
    Resolution_Suggestion: undefined,
    Responsible_Team: "AP Team",
    Auto_Release_Flag: true,
    SLA_Breach_Flag: false,
  },
  {
    Invoice_ID: "INV-1007",
    Vendor_Number: "V500",
    Vendor_Name: "Atlas Supplies",
    Material_Number: "MAT-06",
    Plant: "PL-03",
    PO_Number: "PO-5007",
    PO_Item: "50",
    PO_Type: "Standard",
    GR_Date: "2025-03-20",
    IR_Date: "2025-03-22",
    Match_Date: "2025-04-01",
    Resolution_Date: "2025-04-20",
    Payment_Date: "2025-06-01",
    Payment_Terms: "NET45",
    Match_Status: "FAIL",
    Root_Cause_Code: "PRICE_MISMATCH",
    Tolerance_Pass_Flag: false,
    Exception_Type: "Price Deviation",
    Root_Cause: "Policy",
    Confidence_Score: 0.88,
    Cluster_ID: "C-22",
    Suggested_Action: "Negotiate credit",
    Block_Reason: "Price Block",
    Resolution_Suggestion: "Credit memo",
    Responsible_Team: "Procurement",
    Auto_Release_Flag: false,
    SLA_Breach_Flag: true,
    Block_Date: "2025-04-01",
  },
  {
    Invoice_ID: "INV-1008",
    Vendor_Number: "V200",
    Vendor_Name: "Global Fasteners",
    Material_Number: "MAT-07",
    Plant: "PL-02",
    PO_Number: "PO-5008",
    PO_Item: "10",
    PO_Type: "Service",
    GR_Date: "2025-04-05",
    IR_Date: "2025-04-07",
    Match_Date: "2025-04-08",
    Resolution_Date: "2025-04-10",
    Payment_Date: "2025-05-20",
    Payment_Terms: "NET30",
    Match_Status: "PASS",
    Tolerance_Pass_Flag: false,
    Responsible_Team: "AP Team",
    Auto_Release_Flag: true,
    SLA_Breach_Flag: false,
  },
  {
    Invoice_ID: "INV-1009",
    Vendor_Number: "V600",
    Vendor_Name: "Prime Electronics",
    Material_Number: "MAT-08",
    Plant: "PL-01",
    PO_Number: "PO-5009",
    PO_Item: "10",
    PO_Type: "Standard",
    GR_Date: "2025-04-11",
    IR_Date: "2025-04-12",
    Match_Date: "2025-04-30",
    Resolution_Date: "2025-05-10",
    Payment_Date: "2025-06-20",
    Payment_Terms: "NET45",
    Match_Status: "FAIL",
    Root_Cause_Code: "MISSING_GR",
    Tolerance_Pass_Flag: false,
    Exception_Type: "Missing GR",
    Root_Cause: "System",
    Confidence_Score: 0.45,
    Cluster_ID: "C-08",
    Suggested_Action: "Post GR",
    Block_Reason: "GR Block",
    Resolution_Suggestion: "Initiate GR",
    Responsible_Team: "Warehouse",
    Auto_Release_Flag: false,
    SLA_Breach_Flag: false,
    Block_Date: "2025-04-30",
  },
  {
    Invoice_ID: "INV-1010",
    Vendor_Number: "V100",
    Vendor_Name: "Acme Components",
    Material_Number: "MAT-09",
    Plant: "PL-01",
    PO_Number: "PO-5010",
    PO_Item: "60",
    PO_Type: "Standard",
    GR_Date: "2025-04-20",
    IR_Date: "2025-04-21",
    Match_Date: "2025-05-02",
    Resolution_Date: "2025-05-08",
    Payment_Date: "2025-06-10",
    Payment_Terms: "NET30",
    Match_Status: "TOLERANCE_PASS",
    Root_Cause_Code: "QTY_TOL",
    Tolerance_Pass_Flag: true,
    Exception_Type: "Minor Qty Diff",
    Root_Cause: "Policy",
    Confidence_Score: 0.51,
    Cluster_ID: "C-12",
    Suggested_Action: "Auto-approve",
    Responsible_Team: "AP Team",
    Auto_Release_Flag: true,
    SLA_Breach_Flag: false,
  },
];

export const allVendors = Array.from(new Set(invoices.map(i => i.Vendor_Number)));
export const allMaterials = Array.from(new Set(invoices.map(i => i.Material_Number).filter(Boolean)));
export const allPlants = Array.from(new Set(invoices.map(i => i.Plant).filter(Boolean)));
export const allPOTypes = Array.from(new Set(invoices.map(i => i.PO_Type).filter(Boolean)));
export const allMatchStatuses: MatchStatus[] = ["PASS", "TOLERANCE_PASS", "FAIL"];
export const allExceptionTypes = Array.from(new Set(invoices.map(i => i.Exception_Type).filter(Boolean)));
export const allBlockReasons = Array.from(new Set(invoices.map(i => i.Block_Reason).filter(Boolean)));
export const allTeams = Array.from(new Set(invoices.map(i => i.Responsible_Team).filter(Boolean)));
